# Generated by Django 3.2.5 on 2021-07-14 23:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machines', '0002_machine_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
