@startuml
hide empty description

<style>
stateDiagram {
  arrow {
    LineColor Gray
  }
}
</style>

state locked #ff0000
state open #00ff00
state timed_unlock #ff8000

[*] -> locked
locked --> open: Press White\non Thursday
timed_unlock --> open: Press White\non Thursday
locked -> timed_unlock: Press Green
locked -> timed_unlock: Swipe card/\nPress Leave
open -> locked: Press Red
open -> locked: End of Thursday
timed_unlock -> locked: Press Red/\nTimeout
@enduml
