# Generated by Django 3.2.6 on 2021-08-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_alter_machine_apitoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='user',
        ),
    ]
