# M3x4x4
insert_l = 5
insert_r = (3.5+0.5)/2
insert_sr = 1.5
screw_head_r = 3
screw_head_h = 2.5

# box size
height = 120
width = 150

# distance between wall hanger holes
wh_dist = 80

# shell thickness
th = 4
# shell fillet radius
fillet_r = 5

lid_h = 12
