# M3x4x4
insert_l = 4
insert_r = 2.1
insert_sr = 1.5
screw_head_r = 3
screw_head_h = 2.5

# box size
height = 120
width = 130

# shell thickness
th = 3
# shell fillet radius
fillet_r = 5

# distance between wall hanger holes
wh_dist = 100
