# Generated by Django 3.2.5 on 2021-07-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_log_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='text',
            new_name='message',
        ),
    ]
