# Generated by Django 3.2.6 on 2021-08-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20210816_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='user',
            new_name='user_id',
        ),
    ]
