# Generated by Django 3.2.6 on 2021-08-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_rename_user_log_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='stamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
    ]
