# Generated by Django 3.2.6 on 2021-08-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_alter_log_stamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='machine',
            new_name='machine_id',
        ),
    ]
