# Generated by Django 3.2.6 on 2021-08-16 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_rename_machine_log_machine_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='machine_id',
            new_name='machine',
        ),
    ]
