# Generated by Django 3.2.5 on 2021-07-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='card_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
