# Generated by Django 3.2.6 on 2021-08-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_remove_machine_user'),
        ('members', '0002_member_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='machine',
            field=models.ManyToManyField(blank=True, to='machines.Machine'),
        ),
    ]
