# Generated by Django 3.2.5 on 2021-07-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unknown_cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnknownCards',
            new_name='UnknownCard',
        ),
    ]
