@startuml
hide empty description

state "fatal_error" as fatal

[*] --> locking: handle is raised
[*] --> wait_for_close: handle is not raised
locked --> unlocking: Swipe card
locked --> opening: Press White
opening --> open: Unlocking done
open --> locking: Press Red
open --> unlocked: End of Thursday
unlocking --> unlocked: Unlocking done
unlocking --> fatal: Unlocking failed
unlocked --> alert_unlocked: Timeout
unlocked --> wait_for_enter: Open door
wait_for_enter --> wait_for_handle: Close door
alert_unlocked --> alert_unlocked: Timeout
alert_unlocked --> unlocked: Press Green, Open door
locked --> timed_unlocking: Press Green
timed_unlocking -> timed_unlock: Unlocking done
timed_unlocking --> fatal: Unlocking failed
timed_unlock --> locking: Press Red, Timeout
locking --> locked: Locking done
locking --> fatal: Locking failed
unlocked --> wait_for_lock: Raise handle
locked --> wait_for_leave: Leave pressed
wait_for_lock --> locking: Press Red, Timeout
unlocked --> wait_for_handle: Door closed
unlocked --> wait_for_leave: Press Leave
wait_for_handle --> wait_for_locking: Door opened
wait_for_handle --> wait_for_lock: Raise handle
wait_for_locking --> locking: Raise handle
wait_for_leave --> wait_for_close: Door opened
wait_for_close --> locking: Raise handle
wait_for_close --> unlocked: Press Green
fatal --> [*]
@enduml
